//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// CrystalTile2.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDR_PALETTE                     121
#define IDR_PALETTE2                    122
#define IDR_PALETTE3                    123
#define IDR_PALETTE4                    124
#define IDR_PALETTE5                    125
#define IDR_PALETTE6                    126
#define IDR_PALETTE7                    127
#define IDR_MAINFRAME                   128
#define IDR_CrystalTile2TYPE            129
#define IDS_TOOLBAR                     130
#define IDD_OPENFILEDIALOG              130
#define ID_PROGRESSBAR                  131
#define IDS_OPENFILE                    132
#define IDD_PALETTEDLG                  132
#define IDS_SAVEFILE                    133
#define IDS_OPENROMFILTER               134
#define ID_ROMINFO                      135
#define IDS_OPTIONTREE                  136
#define IDS_TREETAB                     137
#define IDS_CPLIST                      138
#define IDS_LOADPAL                     138
#define IDS_SCALELIST                   139
#define IDC_CT2VIEW_OFFSET              140
#define IDS_LOADMAP                     140
#define IDS_LOADTITLE                   141
#define IDS_TILEFORMATLSIT              142
#define IDD_LZ77SEARCH                  144
#define IDR_CT2POPMENU                  145
#define IDR_LZ77SEARCH                  146
#define IDD_NDSFSI                      147
#define IDD_NDSINFO                     148
#define IDR_NDSFSI                      150
#define IDS_DIBFILTER                   151
#define ID_TILEEDITOR_OFFSET            152
#define IDD_OPENTEXTDLG                 153
#define IDS_ARM9_FOOTER                 154
#define IDS_SAVEAS                      155
#define IDS_PALFILTER                   156
#define IDS_PAL_EXPORTPAL               157
#define IDD_RELATIVEDLG                 159
#define ID_TILEEDITOR_FONT              160
#define IDS_TBLFILTER                   161
#define IDR_AGBCOMP                     161
#define IDS_IMPROTTBL                   162
#define IDD_FILECOMP                    162
#define IDS_OPENMODE                    163
#define IDD_OPTIONBAR                   163
#define IDD_BARPANE                     164
#define IDS_LINECOL                     165
#define IDC_HEXVIEW_TBL                 166
#define IDC_HEXVIEW_BITS                167
#define IDS_NOTFIND                     168
#define IDS_REPLACECOUNT                169
#define IDR_BK1                         169
#define IDS_LZ77HEADTEXT                170
#define IDR_BK2                         170
#define IDS_LZ77SEARCHSTOP              171
#define IDR_BK3                         171
#define IDS_LZ77SEARCHCOUNT             172
#define IDR_BK4                         172
#define IDS_LZ77UNCOMP                  173
#define IDR_BK5                         173
#define IDS_AGBCOMP                     174
#define IDR_BK6                         174
#define IDS_ALLFILE                     175
#define IDR_BK7                         175
#define IDS_COMP                        176
#define IDS_NDSFSIHEADER                177
#define IDS_CRCOK                       178
#define IDS_CRCERROR                    179
#define IDS_SCRIPTVIEW_HEADER           180
#define IDS_SCRIPTIVEW_SEARCHING        181
#define IDC_SCRIPTVIEW_BEGIN            182
#define IDS_SCRIPTFILE                  186
#define IDS_SCRIPTIVEW_FINDPOINT        190
#define IDS_LZ77SEARCH_SEARCHING        191
#define IDS_NODEFHINT                   192
#define IDS_DEFNEWCODE                  193
#define IDS_SWPEXTBL                    194
#define IDS_SWPIMTBL                    195
#define IDS_IMPORTSCRIPT                196
#define IDS_NEWCODE                     197
#define IDC_EDIT_FINDTEXT               199
#define IDS_CODEPAGEHINT                200
#define IDS_DEFCODEPAGE                 201
#define IDS_INVALIDCHAR                 202
#define IDS_IMBMPERROR                  203
#define IDS_FILETOOBIG                  204
#define IDS_FILEOFFERROR                205
#define IDS_RELATIVE_FINDCOUNT          208
#define IDS_RELATIVE_COUNTOUT           209
#define IDS_SIZETOOLONG                 210
#define IDR_VIEW_HEXVIEW                211
#define IDS_FILEISMODIFTED              211
#define IDR_VIEW_TILEEDITORVIEW         212
#define IDS_COMPHEADER                  212
#define IDR_VIEW_SCRIPTVIEW             213
#define IDS_SIZERROR                    213
#define IDS_FILEXIANGTONG               214
#define IDS_COMPING                     215
#define IDS_NDSHEADER                   217
#define IDS_HEXVIEW_HEADER              218
#define IDS_CRYSTALBAR_HIDE             219
#define IDS_OTHERBAR                    223
#define IDS_HEXBAR                      224
#define IDS_SCRIPTBAR                   225
#define IDS_PALETTEDLG                  226
#define IDS_OPTIONBAR                   227
#define IDS_ASMVIEW_HEADER              228
#define IDC_ARM_BASEADDRESS             229
#define IDR_VIEW_ASMVIEW                230
#define IDD_ASMDLG                      230
#define IDS_ASMERROR                    230
#define IDD_FAVORITESBAR                231
#define IDS_FAVORITESBAR                231
#define IDD_INPUTDLG                    232
#define IDS_IMPORTSPECFILE_ERROR        232
#define IDD_SFI                         233
#define IDS_SDATINFOHEADER              233
#define IDS_FSI_FIND                    234
#define IDR_CRYSTALPLAYER               234
#define IDS_SEARCHTEXT_COUNT            235
#define IDD_TOOLSDLG                    235
#define IDS_ASMEXPORT                   236
#define IDD_NET_DIALOG                  236
#define IDS_FSI_SETHEADER               237
#define IDS_FSI_SETSTRUCTSIZE           238
#define IDS_FSI_GOTOHEADER              239
#define IDS_FSI_EXPORTFILEEX            240
#define IDS_PLAYER_NKHZ                 241
#define IDS_NDSHEADERINFO               242
#define IDS_NDSCWDH_INFO                243
#define IDS_NDSCGLP_INFO                245
#define IDS_NEWTOOL                     246
#define IDS_EXEC                        247
#define IDS_MAXTOOL                     248
#define IDS_BREAKOPEN                   249
#define IDS_BREAKSAVE                   250
#define IDS_TOOLBAREX                   251
#define IDS_SETNFTRWH                   252
#define IDS_PCMEM_ERROR                 254
#define IDD_CHEATS                      254
#define IDS_DSMEM                       255
#define IDR_NINTENDOLOGO                255
#define IDS_CHEATSHEADER                256
#define IDR_DSEMU_MENURES               256
#define IDS_CHANGECHEATS                257
#define IDR_SFI                         257
#define IDS_ADDCHEATS                   258
#define IDR_TD_TILEVIEW                 258
#define IDR_TD_HEXVIEW                  259
#define IDS_DSMENU2CHS                  259
#define IDR_TD_ASMVIEW                  260
#define IDS_NOPROCESS                   260
#define IDR_TD_EDITORVIEW               261
#define IDR_TD_SCRIPTVIEW               262
#define IDR_ANGELLOGO                   263
#define IDS_SFI_MENUTEXT                264
#define IDS_SFI_HEADER                  265
#define IDD_DS_FIRMWARE                 265
#define IDS_SFI_UTILITY_HEADER          266
#define IDS_SFI_NORMAL_IMPORTERR        267
#define IDS_SFI_IMPORTERR               268
#define IDR_MENU1                       268
#define ID_CODEPAGE_ACP                 600
#define IDC_VERINFO                     1005
#define IDC_SETCOLORBTN                 1006
#define IDC_SETBKCOLORBTN               1007
#define IDC_SETSHADOWCOLORBTN           1008
#define IDC_SETPALPANEL                 1009
#define IDC_DEFPALBTN                   1010
#define IDC_LOADPALBTN                  1011
#define IDC_SAVEPALBTN                  1012
#define IDC_CODEPAGELIST                1012
#define IDC_COMP_FILEONE                1013
#define IDC_COMP_FILETWO                1014
#define IDC_COMP_FILEONEBTN             1015
#define IDC_COMP_FILETWOBTN             1016
#define IDC_COMPLIST                    1017
#define IDC_COMP_COMFILE                1018
#define IDC_OPENTEXTEDIT                1019
#define IDC_MAILTO                      1039
#define IDC_HOMEPAGE                    1040
#define IDC_FAVORITES_DESC              1041
#define IDC_OPTION_CPLIST               1042
#define IDC_OPTION_PALLIST              1043
#define IDC_ASMCB                       1043
#define IDC_OPTION_BKLIST               1044
#define IDC_ASMHINT                     1044
#define IDC_OPTION_OFFSETLIST           1045
#define IDC_ASMDESC                     1045
#define IDC_FAVORITES_ADDBTN            1046
#define IDC_FAVORITES_LIST              1047
#define IDC_FAVORITES_DELBTN            1048
#define IDC_FLOATCHECK                  1051
#define IDC_INPUTDLG_EDIT               1052
#define IDC_INPUTDLG_HINT               1053
#define IDC_SFI_FILELIST                1054
#define IDC_TOOLS_LIST                  1055
#define IDC_TOOLS_ADDBTN                1056
#define IDC_TOOLS_DELBTN                1057
#define IDC_TOOLS_UPBTN                 1058
#define IDC_TOOLS_DOWNBTN               1059
#define IDC_TOOLS_TITLEEDIT             1060
#define IDC_TOOLS_COMMANDEDIT           1061
#define IDC_TOOLS_PATHBTN               1062
#define IDC_MFILELIST                   1062
#define IDC_TOOLS_REDIT                 1063
#define IDC_MFILE_OPEN                  1063
#define IDC_NET_SENDMSG                 1064
#define IDC_MSGLIST                     1065
#define IDC_SENDMSGEDIT                 1066
#define IDC_USERLIST                    1068
#define IDC_CHEATS_SEARCHDATA           1069
#define IDC_CHEATS_SEARCH               1070
#define IDC_CHEATS_LIST                 1071
#define IDC_CHEATS_DATATYPE8            1072
#define IDC_CHEATS_DATATYPE16           1073
#define IDC_CHEATS_DATATYPE32           1074
#define IDC_CHEATS_DEC                  1075
#define IDC_CHEATS_HEX                  1076
#define IDC_CHEATS_SEARCH2              1077
#define IDC_CHEATS_LOCKLIST             1078
#define IDC_FINDLIST                    1079
#define IDC_CHEATS_SAVE                 1079
#define IDC_RESULTLIST                  1080
#define IDC_COMBO1                      1080
#define IDC_COMBO_DS_FIRMWARE_LANG      1080
#define IDC_CHEATS_DEL                  1080
#define IDC_4BITRADIO                   1081
#define IDC_DEF_RESPATH                 1081
#define IDC_1BITRADIO                   1082
#define IDC_BUTTON_RESPATH              1082
#define IDC_2BITRADIO                   1083
#define IDC_DSFIRMWARE_NICKNAME         1083
#define IDC_CHEATS_ADD                  1083
#define IDC_VALEDIT                     1084
#define IDC_DSFIRMWARE_MESSAGE          1084
#define IDC_ADDBTN                      1085
#define IDC_DSFIRMWARE_BIRTHDAY         1085
#define IDC_DELBTN                      1086
#define IDC_BUTTON_OPENFIRMWARE         1086
#define IDC_DECRADIO                    1087
#define IDC_DSFIRMWARE_COLOR            1087
#define IDC_HEXRADIO                    1088
#define IDC_RADIO_DSFIRMWARE_1          1088
#define IDC_STRRADIO                    1089
#define IDC_RADIO2                      1089
#define IDC_RADIO_DSFIRMWARE_2          1089
#define IDC_FINDBTN                     1090
#define IDC_NEXTBTN                     1091
#define IDC_CLRBTN                      1091
#define IDC_SAVEBTN                     1092
#define IDC_SWPCHECK                    1093
#define IDC_OFFCHECK                    1095
#define IDC_STARTEDIT                   1120
#define IDC_ENDEDIT                     1121
#define IDC_MAPFILE                     1131
#define IDC_FALGEDIT                    1132
#define IDC_SIZELOW                     1133
#define IDC_SIZEHI                      1134
#define IDC_STEPEDIT                    1135
#define IDC_DOWNCHECK                   1136
#define IDC_LZ77CHECK                   1137
#define IDC_RETLIST                     1138
#define IDC_LZ77SAVEBTN                 1139
#define IDC_JPNBTN                      1139
#define IDC_USBTN                       1140
#define IDC_FSILIST                     1141
#define IDC_FREBTN                      1141
#define IDC_GEBTN                       1142
#define IDC_ITABTN                      1143
#define IDC_SPABTN                      1144
#define IDC_NDSINFOEDIT                 1145
#define IDC_ENTRYINFO                   1158
#define ID_TOOLS_ZOOMEXFIRST            32560
#define ID_VIEW_TILEVIEW                32772
#define ID_VIEW_HEXVIEW                 32773
#define ID_VIEW_ASMVIEW                 32774
#define ID_VIEW_TILEEDITORVIEW          32775
#define ID_VIEW_SCRIPTVIEW              32776
#define ID_VIEW_GRID                    32780
#define ID_TTB_PAL                      32781
#define ID_EDIT_EXPORT                  32795
#define ID_EDIT_IMPORT                  32804
#define ID_TILEEDITOR_TEXT              32818
#define ID_VIEW_AUTOFITCOL              32826
#define ID_TILEEDITOR_TBL               32827
#define ID_SETCOLOR_TEXTCOLOR           32844
#define ID_SETCOLOR_BKCOLOR             32846
#define ID_SETCOLOR_SHADOWCOLOR         32848
#define ID_TBL_SELTBL                   32864
#define ID_VIEW_2BYTEALIGN              32870
#define ID_VIEW_4BYTEALIGN              32871
#define ID_VIEW_COLORTEXT               32873
#define IDC_HEXVIEW_SETBITS             32877
#define ID_HEXVIEW_SWPCODE              32880
#define ID_SEARCH_FIND                  32888
#define ID_SEARCH_REPLACE               32890
#define ID_SEARCH_FINDNEXT              32895
#define ID_EDIT_DATA2PAL                32899
#define ID_EDIT_PAL2DATA                32900
#define ID_HEXVIEW_IMPORT               32901
#define ID_SEARCH_LZ77                  32904
#define ID_TOOLS_LZ77UNCOMP             32906
#define ID_TOOLS_LZ77COMP               32908
#define ID_LZ77_UNCOMPALL               32909
#define ID_LZ77_UNCOMPSEL               32910
#define ID_LZ77_BREAK                   32911
#define ID_LZ77_DELETE                  32912
#define ID_FSI_GO                       32913
#define ID_FSI_REFALSH                  32914
#define ID_FSI_EXPORT                   32915
#define ID_FSI_IMPORT                   32916
#define ID_FSI_SPLITROM                 32917
#define ID_FSI_CREATEROM                32918
#define ID_FSI_CHECKCRC16               32919
#define ID_FSI_GAMEINFO                 32920
#define ID_TOOLS_NDSFSI                 32930
#define ID_FSI_GOFILE                   32936
#define ID_SEARCH_TEXT                  32942
#define ID_SEARCH_TEXTEX                32943
#define ID_SCRIPTVIEW_FINDPOINT         32948
#define ID_EDIT_DELETE                  32949
#define ID_SCRIPTVIEW_INVALIDATEDELETE  32951
#define ID_SEARCH_ALIGN2                32953
#define ID_SEARCH_NOWORD                32957
#define ID_SCRIPTVIEW_OPENSCRIPT        32960
#define ID_SCRIPTVIEW_FILTERPOINT       32962
#define ID_SCRIPTVIEW_FILTERSITEM       32964
#define ID_SCRIPTVIEW_FILTERDITEM       32966
#define ID_SCRIPTVIEW_FILTERMIN         32968
#define ID_SCRIPTVIEW_FILTERMAX         32970
#define ID_SCRIPTVIEW_FILTERSADDRESS    32972
#define ID_SCRIPTVIEW_FILTERDADDRESS    32974
#define ID_SCRIPTVIEW_FILTERCHECKWORD   32976
#define ID_SCRIPTVIEW_FILTERSPECWORD    32978
#define ID_SCRIPTVIEW_FILTERACHECK      32980
#define ID_SCRIPTVIEW_CHECKALL          32984
#define ID_SCRIPTVIEW_FILTERUNCHECK     32986
#define ID_SCRIPTVIEW_DELCHECKITEM      32988
#define ID_SCRIPTVIEW_EXPORTCHECKITEM   32990
#define ID_SEARCH_RELATIVE              32992
#define ID_TOOLS_FILECOMP               33037
#define ID_SEARCH_CTRLENDONLY           33044
#define ID_TBL_TOTALWORD                33047
#define ID_TOOLS_TEXTCPCHANGE           33049
#define ID_PALETTE_PAL1                 33073
#define ID_PALETTE_PAL2                 33074
#define ID_PALETTE_PAL3                 33075
#define ID_PALETTE_PAL4                 33076
#define ID_PALETTE_PAL5                 33077
#define ID_PALETTE_PAL6                 33078
#define ID_PALETTE_PAL7                 33079
#define ID_VIEW_BK1                     33080
#define ID_VIEW_BK2                     33081
#define ID_VIEW_BK3                     33082
#define ID_VIEW_BK4                     33083
#define ID_VIEW_BK5                     33084
#define ID_VIEW_BK6                     33085
#define ID_VIEW_BK7                     33086
#define ID_FSI_SETMAP                   33113
#define ID_EDIT_RESET                   33119
#define ID_ARM_ARM9_ARM                 33123
#define ID_ARM_ARM9_THUMB               33124
#define ID_ARM_ARM7_ARM                 33125
#define ID_ARM_ARM7_THUMB               33126
#define IDC_HEXVIEW_TBLCTRL             33135
#define ID_TOOLS_SFI                    33138
#define ID_FSI_FIND                     33143
#define ID_FSI_COPYTOCLIPBOARD          33147
#define ID_FSI_NEXT                     33149
#define ID_FSI_GOHAN                    33151
#define ID_WINDOW_OPTIONTREE            33157
#define ID_WINDOW_PALOPTION             33158
#define ID_WINDOW_DEFOPTION             33159
#define ID_FSI_GOARM9                   33168
#define ID_FSI_GOARM7                   33169
#define ID_ASM_FOLLOW                   33171
#define ID_ASM_UNFOLLOW                 33173
#define ID_FSI_EXPORTEX                 33184
#define ID_PLAYER_MONO                  33204
#define ID_PLAYER_STEREO                33205
#define ID_PLAYER_4BIT                  33206
#define ID_PLAYER_8BIT                  33207
#define ID_PLAYER_16BIT                 33208
#define ID_PLAYER_11KHZ                 33209
#define ID_PLAYER_22KHZ                 33210
#define ID_PLAYER_44KHZ                 33211
#define ID_PLAYER_48KHZ                 33212
#define ID_PLAYER_96KHZ                 33213
#define ID_PLAYER_NKHZ                  33214
#define ID_PLAYER_PLAY                  33215
#define ID_PLAYER_STOP                  33217
#define ID_VIEW_TOOLEX                  33223
#define ID_FONT_LIST                    33224
#define ID_FSIPOP_LOADNTFRWH            33231
#define ID_FSIPOP_SETNTFRWH             33232
#define ID_EDIT_MEMREFALSH              33243
#define ID_TOOLS_CHEATSSERACH           33248
#define ID_EDIT_EXPORT_EX               33250
#define ID_FSIPOP_EXPORTTBL             33257
#define ID_TOOLS_TBL2CMAP               33259
#define ID_SFI_EXPORT                   33277
#define ID_SFI_IMPORT                   33281
#define ID_SFI_REFLASH                  33284
#define ID_VIEW_OPTIONBAR               33287
#define ID_ACCELERATOR33292             33292
#define ID_ACCEL_BREAK                  33292
#define ID_FSIPOP_LOADICONPAL           33296
#define ID_FSIPOP_SHOWICON              33297
#define ID_FSIPOP_UPDATEICONPAL         33299
#define ID_TOOLS_GETCRC16               33301
#define ID_TOOLS_NDS_FIRMWARE           33303
#define ID_FSI_FIX                      33305
#define ID_33306                        33306
#define ID_FSI_LOADDATA                 33307
#define ID_FAVORITES_ADD                34000
#define ID_FSI_SETFILESIZE              35000
#define ID_FSI_GOTOHEADER               36000
#define ID_TOOLS_TOOLS                  37000
#define ID_FILE_FIRSTDSEMUTASK          37033

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        269
#define _APS_NEXT_COMMAND_VALUE         33308
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
